import 'package:dto/game.dart';

List<Game> games = [
  Game(
    gameId: 'game1',
    playerWhite: 'janjaTheGoat',
    playerBlack: 'adam',
    currentTurn: 'white',
    gameState: 'ongoing',
    moves: ['e2e4', 'e7e5', 'g1f3'],
    boardState: [
      'r', 'n', 'b', 'q', 'k', 'b', 'n', 'r',
      'p', 'p', 'p', null, 'p', 'p', 'p', 'p',
      null, null, null, null, null, null, null, null,
      null, null, null, 'p', null, null, null, null,
      null, null, null, 'P', null, null, null, null,
      null, null, 'N', null, null, null, null, null,
      'P', 'P', 'P', null, 'P', 'P', 'P', 'P',
      'R', null, 'B', 'Q', 'K', 'B', 'N', 'R',
    ],
  ),
  Game(
    gameId: 'game2',
    playerWhite: 'antoine',
    playerBlack: 'LightningBolt',
    currentTurn: 'white',
    gameState: 'ongoing',
    moves: ['d2d4', 'd7d5', 'c2c4'],
    boardState: [
      'r', null, 'b', 'q', 'k', 'b', null, 'r',
      'p', 'p', 'p', 'p', null, 'p', 'p', 'p',
      null, null, 'n', null, null, 'n', null, null,
      null, null, null, null, 'p', null, null, 'Q',
      null, null, 'B', null, 'P', null, null, null,
      null, null, null, null, null, null, null, null,
      'P', 'P', 'P', 'P', null, 'P', 'P', 'P',
      'R', 'N', 'B', null, 'K', null, 'N', 'R',
    ],
  ),
  Game(
    gameId: 'game3',
    playerWhite: 'MM',
    playerBlack: 'CabeiBusha',
    currentTurn: 'white',
    gameState: 'ongoing',
    moves: ['f2f4', 'e7e6', 'g1f3'],
    boardState: [
      'r', 'n', 'b', 'q', 'k', 'b', 'n', 'r',
      'p', 'p', 'p', 'p', null, 'p', 'p', 'p',
      null, null, null, null, 'p', null, null, null,
      null, null, null, null, null, null, null, null,
      null, null, 'P', 'P', null, null, null, null,
      null, null, null, null, null, 'N', null, null,
      'P', 'P', null, 'P', 'P', 'P', 'P', 'P',
      'R', 'N', 'B', 'Q', 'K', 'B', null, 'R',
    ],
  ),
];
