import 'package:dto/user.dart';

List<User> users = [
  User(
      username: 'adam',
      fullName: "Adam Ondra",
      nationality: "",
      profilePicture: "gs://flutter-chess-1af50.appspot.com/janja_garnbret.jpg",
      email: "Adam@example.com",
      friends: ['janjaTheGoat', 'LightningBolt'],
      sentFriendRequests: [],
      receivedFriendRequests: [],
      sentChallengeRequests: [],
      receivedChallengeRequests:[]
  ),
  User(
      username: 'janjaTheGoat',
      fullName: "Janja Garnbret",
      nationality: "République Tchèque",
      profilePicture: "",
      email: "Janja@example.com",
      friends: ['adam', 'antoine'],
      sentFriendRequests: ['LightningBolt', 'CabeiBusha'],
      receivedFriendRequests: ['MM'],
      sentChallengeRequests: [],
      receivedChallengeRequests:['antoine']),
  User(
      username: 'antoine',
      fullName: "Antoine Albeau",
      nationality: "",
      profilePicture: "",
      email: "Antoine@example.com",
      friends: ['janjaTheGoat'],
      sentFriendRequests: [],
      receivedFriendRequests: ['LightningBolt'],
      sentChallengeRequests: ['janjaTheGoat'],
      receivedChallengeRequests:[]),
  User(
      username: 'LightningBolt',
      fullName: "Usain Bolt",
      nationality: "",
      profilePicture: "",
      email: "Usain@example.com",
      friends: ['adam', 'CabeiBusha'],
      sentFriendRequests: ['antoine'],
      receivedFriendRequests: ['janjaTheGoat'],
      sentChallengeRequests: [],
      receivedChallengeRequests:[]),
  User(
      username: 'MM',
      fullName: "Magnus Mitbø",
      nationality: "",
      profilePicture: "",
      email: "Magnus@example.com",
      friends: [],
      sentFriendRequests: ['janjaTheGoat'],
      receivedFriendRequests: ['CabeiBusha'],
      sentChallengeRequests: [],
      receivedChallengeRequests:[]),
  User(
      username: 'CabeiBusha',
      fullName: "Sarah-Quita Offringa",
      nationality: "",
      profilePicture: "",
      email: "SarahQuita@example.com",
      friends: ['LightningBolt'],
      sentFriendRequests: ['MM'],
      receivedFriendRequests: ['janjaTheGoat'],
      sentChallengeRequests: [],
      receivedChallengeRequests:[]),
];
